=== rbute/BCIUI/settings/settings.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT settings (title,singleton+,groups+,polygon*)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT singleton (symbol+,(polygon+|(xml:polygon)+))>
<!ELEMENT symbol (#PCDATA)>

<!ELEMENT polygon (point+)>
<!ELEMENT point (coordinate,coordinate)>
<!ELEMENT coordinate (#PCDATA)>

<!ELEMENT groups (groupName,group*) >
<!ATTLIST groups type CDATA (P300,SSVEP) "SSVEP" >

<!ELEMENT groupName (#PCDATA)>
<!ELEMENT group (timePeriod,dutyCycle,singleton*)>
<!ELEMENT timePeriod (#PCDATA)>
<!ELEMENT dutyCycle (#PCDATA)>

=== rbute/BCIUI/settings/test.xml
<!DOCTYPE settings SYSTEM "C:\214EC3011\PRLab\BCIUI\settings\settings.dtd">
<settings>
	<title >Brain Computer Interface Default Settings
		title
	</title>
	<singleton>
		<symbol>symbol</symbol>
		<polygon>
			<point>
				<coordinate>coordinate</coordinate>
				<coordinate>coordinate</coordinate>
			</point>
		</polygon>
		<polygon>
			<point>
				<coordinate>coordinate</coordinate>
				<coordinate>coordinate</coordinate>
			</point>
		</polygon>
	</singleton>
	<groups>
		<groupName ></groupName>
		<group />
	</groups>
	<polygon>
		<point>
			<coordinate>coordinate</coordinate>
			<coordinate>coordinate</coordinate>
		</point>
	</polygon>

</settings>
